// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGh-MdwHaivtDWfL1emuQImi3P6r0h5N4',
    appId: '1:772702001257:web:bf82b571f2c0495602aaf8',
    messagingSenderId: '772702001257',
    projectId: 'nitish-396208',
    authDomain: 'nitish-396208.firebaseapp.com',
    databaseURL: 'https://nitish-396208-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nitish-396208.appspot.com',
    measurementId: 'G-X11CXS22DK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-sO47dHp2peq82amq0rxbgMAQ9qpm_do',
    appId: '1:772702001257:android:a1c48e24e3b3816402aaf8',
    messagingSenderId: '772702001257',
    projectId: 'nitish-396208',
    databaseURL: 'https://nitish-396208-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nitish-396208.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcnSG852YSrbC8kEanP_i629it-BlXcnw',
    appId: '1:772702001257:ios:44d4141c0745240d02aaf8',
    messagingSenderId: '772702001257',
    projectId: 'nitish-396208',
    databaseURL: 'https://nitish-396208-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nitish-396208.appspot.com',
    iosBundleId: 'com.example.qrScanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcnSG852YSrbC8kEanP_i629it-BlXcnw',
    appId: '1:772702001257:ios:ec599973132344eb02aaf8',
    messagingSenderId: '772702001257',
    projectId: 'nitish-396208',
    databaseURL: 'https://nitish-396208-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nitish-396208.appspot.com',
    iosBundleId: 'com.example.qrScanner.RunnerTests',
  );
}
